/**
 * Parameter definitions for the art application
 * Each parameter defines the configuration for a controllable aspect of the art generation
 */

export const PARAMETERS = [
  {
    id: 'speed',
    label: 'Speed',
    type: 'slider',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 0.002,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Animation',
    transform: {
      // Convert speed to/from slider (quartic scaling like original)
      toSlider: (value) => Math.pow(value / 0.1, 1 / 4),
      fromSlider: (value) => Math.pow(value, 4) * 0.1
    }
  },
  {
    id: 'variation',
    label: 'Layer Variation',
    type: 'slider',
    min: 0,
    max: 3,
    step: 0.1,
    defaultValue: 0.2,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Animation',
  },
  {
    id: 'numLayers',
    label: 'Number of Layers',
    type: 'slider',
    min: 1,
    max: 20,
    step: 1,
    defaultValue: 1,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Layers',
  },
  {
    id: 'guideWidth',
    label: 'Guide Width',
    type: 'slider',
    min: 10,
    max: 900,
    step: 10,
    defaultValue: 250,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'guideHeight',
    label: 'Guide Height',
    type: 'slider',
    min: 10,
    max: 900,
    step: 10,
    defaultValue: 250,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'curviness',
    label: 'Wobble',
    type: 'slider',
    min: 0.3,
    max: 1.5,
    step: 0.05,
    defaultValue: 0.5,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'noiseAmount',
    label: 'Noise',
    type: 'slider',
    min: 0,
    max: 8,
    step: 0.1,
    defaultValue: 0.5,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'numSides',
    label: 'Sides',
    type: 'slider',
    min: 3,
    max: 20,
    step: 1,
    defaultValue: 6,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'globalOpacity',
    label: 'Opacity',
    type: 'slider',
    min: 0,
    max: 1,
    step: 0.1,
    defaultValue: 0.8,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Appearance',
  },
  {
    id: 'blendMode',
    label: 'Blend Mode',
    type: 'dropdown',
    options: ['source-over', 'multiply', 'screen', 'overlay', 'lighter', 'soft-light', 'hard-light', 'color-dodge'],
    defaultValue: 'source-over',
    isRandomizable: true,
    showInOverlay: true,
    group: 'Appearance',
  },
  {
    id: 'backgroundColor',
    label: 'Background',
    type: 'color',
    defaultValue: '#000000',
    isRandomizable: true,
    showInOverlay: true,
    group: 'Appearance',
  },
  {
    id: 'seed',
    label: 'Seed',
    type: 'number',
    min: 0,
    max: 10000,
    step: 1,
    defaultValue: Math.floor(Math.random() * 10000),
    isRandomizable: true,
    showInOverlay: true,
    group: 'Random',
  }
];