export const SOUNDSCAPE_SOURCES = Object.freeze({
  speed: { label: 'Speed', defaultSmoothing: 0.3 },
  layers: { label: 'Layer count', defaultSmoothing: 0.35 },
  density: { label: 'Layer density', defaultSmoothing: 0.35 },
  chaos: { label: 'Layer chaos', defaultSmoothing: 0.25 },
  size: { label: 'Size', defaultSmoothing: 0.45 },
  opacity: { label: 'Opacity', defaultSmoothing: 0.25 },
  noise: { label: 'Noise', defaultSmoothing: 0.2 },
  blend: { label: 'Difference blend', defaultSmoothing: 0.2 },
  curviness: { label: 'Curviness', defaultSmoothing: 0.35 },
  wobble: { label: 'Wobble', defaultSmoothing: 0.25 },
  sides: { label: 'Sides', defaultSmoothing: 0.4 },
  tension: { label: 'Tension', defaultSmoothing: 0.3 },
  backgroundLightness: { label: 'Background lightness', defaultSmoothing: 0.5 },
});

export const SOUNDSCAPE_DESTINATIONS = Object.freeze({
  bpm: { label: 'Tempo', min: 42, max: 180, step: 1, combine: 'replace' },
  masterGain: { label: 'Master response', min: 0.2, max: 1, step: 0.01, combine: 'multiply' },
  reverbWet: { label: 'Reverb amount', min: 0.08, max: 0.96, step: 0.01, combine: 'replace' },
  distortion: { label: 'Distortion', min: 0, max: 0.75, step: 0.01, combine: 'replace' },
  filterFrequency: { label: 'Main filter', min: 180, max: 5000, step: 10, combine: 'add' },
  filterQ: { label: 'Filter resonance', min: 0.5, max: 10, step: 0.1, combine: 'replace' },
  noiseFilterFrequency: { label: 'Noise filter', min: 150, max: 3000, step: 10, combine: 'replace' },
  noiseVolume: { label: 'Noise level', min: -52, max: -16, step: 1, combine: 'replace' },
  padLevel: { label: 'Pad level', min: 0.35, max: 1.15, step: 0.01, combine: 'multiply' },
  stereoSpread: { label: 'Stereo spread', min: 0.2, max: 1, step: 0.01, combine: 'replace' },
  detuneAmount: { label: 'Pitch movement', min: 0.02, max: 2.4, step: 0.01, combine: 'add' },
});

export const DEFAULT_SOUNDSCAPE_ROUTES = Object.freeze([
  { id: 'speed-bpm', source: 'speed', dest: 'bpm', inMin: 0, inMax: 1, outMin: 42, outMax: 162, curve: 'linear', invert: false, depth: 1, smoothing: 0.3 },
  { id: 'opacity-master', source: 'opacity', dest: 'masterGain', inMin: 0, inMax: 1, outMin: 0.25, outMax: 1, curve: 'linear', invert: false, depth: 1, smoothing: 0.25 },
  { id: 'size-reverb', source: 'size', dest: 'reverbWet', inMin: 0, inMax: 1, outMin: 0.08, outMax: 0.96, curve: 'linear', invert: false, depth: 1, smoothing: 0.45 },
  { id: 'noise-distortion', source: 'noise', dest: 'distortion', inMin: 0, inMax: 1, outMin: 0, outMax: 0.75, curve: 'exp', invert: false, depth: 1, smoothing: 0.2 },
  { id: 'curviness-filter', source: 'curviness', dest: 'filterFrequency', inMin: 0, inMax: 1, outMin: 240, outMax: 2440, curve: 'log', invert: false, depth: 1, smoothing: 0.35 },
  { id: 'tension-filter', source: 'tension', dest: 'filterFrequency', inMin: 0, inMax: 1, outMin: 0, outMax: 1800, curve: 'linear', invert: false, depth: 1, smoothing: 0.25 },
  { id: 'wobble-q', source: 'wobble', dest: 'filterQ', inMin: 0, inMax: 1, outMin: 0.5, outMax: 7.5, curve: 'linear', invert: false, depth: 1, smoothing: 0.25 },
  { id: 'background-noise-filter', source: 'backgroundLightness', dest: 'noiseFilterFrequency', inMin: 0, inMax: 1, outMin: 180, outMax: 1480, curve: 'log', invert: false, depth: 1, smoothing: 0.5 },
  { id: 'noise-level', source: 'noise', dest: 'noiseVolume', inMin: 0, inMax: 1, outMin: -48, outMax: -20, curve: 'exp', invert: false, depth: 1, smoothing: 0.25 },
  { id: 'layers-pad-level', source: 'layers', dest: 'padLevel', inMin: 0, inMax: 1, outMin: 1, outMax: 0.62, curve: 'linear', invert: false, depth: 1, smoothing: 0.35 },
  { id: 'layers-spread', source: 'layers', dest: 'stereoSpread', inMin: 0, inMax: 1, outMin: 0.55, outMax: 1, curve: 'linear', invert: false, depth: 1, smoothing: 0.35 },
  { id: 'density-spread', source: 'density', dest: 'stereoSpread', inMin: 0, inMax: 1, outMin: 0.55, outMax: 1, curve: 'linear', invert: false, depth: 0.75, smoothing: 0.35 },
  { id: 'chaos-distortion', source: 'chaos', dest: 'distortion', inMin: 0.58, inMax: 1, outMin: 0, outMax: 0.5, curve: 'exp', invert: false, depth: 0.7, smoothing: 0.2 },
  { id: 'chaos-noise-level', source: 'chaos', dest: 'noiseVolume', inMin: 0, inMax: 1, outMin: -48, outMax: -18, curve: 'exp', invert: false, depth: 0.65, smoothing: 0.25 },
  { id: 'density-detune', source: 'density', dest: 'detuneAmount', inMin: 0.4, inMax: 1, outMin: 0, outMax: 0.9, curve: 'exp', invert: false, depth: 0.65, smoothing: 0.25 },
  { id: 'wobble-detune', source: 'wobble', dest: 'detuneAmount', inMin: 0, inMax: 1, outMin: 0.02, outMax: 1.2, curve: 'exp', invert: false, depth: 1, smoothing: 0.25 },
  { id: 'tension-detune', source: 'tension', dest: 'detuneAmount', inMin: 0, inMax: 1, outMin: 0, outMax: 1.2, curve: 'exp', invert: false, depth: 1, smoothing: 0.25 },
]);

export const SOUND_PROGRAMS = Object.freeze({
  glass: {
    name: 'Glass',
    padOscillator: 'sine2',
    droneOscillator: 'sine',
    filterOffset: 980,
    filterQOffset: 0.15,
    reverbOffset: 0.12,
    noiseType: 'pink',
    noiseOffset: -12,
    octaveOffset: 12,
    attack: 2.6,
    release: 4.8,
    voiceGain: 0.86,
    motionDepth: 0.68,
    stereoWidth: 1,
    droneLevelOffset: -4,
  },
  velvet: {
    name: 'Velvet',
    padOscillator: 'sine',
    droneOscillator: 'sine',
    filterOffset: -520,
    filterQOffset: -0.35,
    reverbOffset: 0.1,
    noiseType: 'brown',
    noiseOffset: -14,
    octaveOffset: 0,
    attack: 3.4,
    release: 5.5,
    voiceGain: 0.95,
    motionDepth: 0.45,
    stereoWidth: 0.72,
    droneLevelOffset: 2,
  },
  prism: {
    name: 'Prism',
    padOscillator: 'triangle2',
    droneOscillator: 'sine2',
    filterOffset: 620,
    filterQOffset: 1.1,
    reverbOffset: 0.02,
    noiseType: 'pink',
    noiseOffset: -8,
    octaveOffset: 12,
    attack: 1.35,
    release: 2.8,
    voiceGain: 0.78,
    motionDepth: 1,
    stereoWidth: 1,
    droneLevelOffset: -7,
  },
  tide: {
    name: 'Tide',
    padOscillator: 'sine2',
    droneOscillator: 'sine',
    filterOffset: -120,
    filterQOffset: 0.25,
    reverbOffset: 0.22,
    noiseType: 'brown',
    noiseOffset: -6,
    octaveOffset: 0,
    attack: 2.9,
    release: 6.2,
    voiceGain: 0.9,
    motionDepth: 0.85,
    stereoWidth: 0.9,
    droneLevelOffset: 1,
  },
  ember: {
    name: 'Ember',
    padOscillator: 'triangle',
    droneOscillator: 'triangle',
    filterOffset: 260,
    filterQOffset: 1.35,
    reverbOffset: -0.04,
    noiseType: 'brown',
    noiseOffset: -2,
    octaveOffset: -12,
    attack: 0.9,
    release: 2.4,
    voiceGain: 0.82,
    motionDepth: 1.15,
    stereoWidth: 0.82,
    droneLevelOffset: 4,
  },
  aurora: {
    name: 'Aurora',
    padOscillator: 'sine4',
    droneOscillator: 'sine2',
    filterOffset: 760,
    filterQOffset: 0.6,
    reverbOffset: 0.14,
    noiseType: 'pink',
    noiseOffset: -10,
    octaveOffset: 0,
    attack: 4.2,
    release: 7,
    voiceGain: 0.84,
    motionDepth: 0.62,
    stereoWidth: 1,
    droneLevelOffset: -3,
  },
});

export const DEFAULT_PROGRAM_IDS = Object.freeze(Object.keys(SOUND_PROGRAMS));
