import { z } from 'zod';

export const parameterSchema = z.object({
  id: z.string(),
  label: z.string(),
  type: z.enum(['slider', 'dropdown', 'toggle', 'global']).optional(),
  min: z.number().optional(),
  max: z.number().optional(),
  step: z.number().optional(),
  defaultValue: z.union([z.number(), z.string(), z.boolean()]).optional(),
  options: z.array(z.union([z.string(), z.number()])).optional(),
  isRandomizable: z.boolean().default(false),
  showInOverlay: z.boolean().optional(),
  group: z.string().optional(),
  randomMin: z.number().optional(),
  randomMax: z.number().optional(),
  description: z.string().optional(),
}).passthrough();

export const parameterArraySchema = z.array(parameterSchema);
export type Parameter = z.infer<typeof parameterSchema>;

const positionSchema = z.object({
  centerX: z.number().optional(),
  centerY: z.number().optional(),
  x: z.number().min(-1).max(2).default(0.5),
  y: z.number().min(-1).max(2).default(0.5),
  vx: z.number().default(0),
  vy: z.number().default(0),
  scale: z.number().min(0).max(10).default(1),
  scaleDirection: z.union([z.literal(-1), z.literal(1)]).default(1),
});

const layerVariationSchema = z.object({
  numSides: z.boolean().optional(),
  curviness: z.boolean().optional(),
  wobble: z.boolean().optional(),
  noiseAmount: z.boolean().optional(),
  radiusFactor: z.boolean().optional(),
  radiusFactorX: z.boolean().optional(),
  radiusFactorY: z.boolean().optional(),
  xOffset: z.boolean().optional(),
  yOffset: z.boolean().optional(),
  width: z.boolean().optional(),
  height: z.boolean().optional(),
  opacity: z.boolean().optional(),
  movementStyle: z.boolean().optional(),
  movementSpeed: z.boolean().optional(),
  movementAngle: z.boolean().optional(),
  scaleSpeed: z.boolean().optional(),
  scaleMin: z.boolean().optional(),
  scaleMax: z.boolean().optional(),
  orbitCenterX: z.boolean().optional(),
  orbitCenterY: z.boolean().optional(),
  orbitRadiusX: z.boolean().optional(),
  orbitRadiusY: z.boolean().optional(),
  freq1: z.boolean().optional(),
  freq2: z.boolean().optional(),
  freq3: z.boolean().optional(),
  imageBlur: z.boolean().optional(),
  imageBrightness: z.boolean().optional(),
  imageContrast: z.boolean().optional(),
  imageHue: z.boolean().optional(),
  imageSaturation: z.boolean().optional(),
  imageDistortion: z.boolean().optional(),
  colors: z.boolean().optional(),
  numColors: z.boolean().optional(),
  colorFadeEnabled: z.boolean().optional(),
  colorFadeSpeed: z.boolean().optional(),
});

export const layerSchema = z.object({
  id: z.string().min(1).optional(),
  name: z.string().optional(),
  layerType: z.enum(['shape', 'image']).default('shape'),
  imageSrc: z.string().nullable().optional(),
  shapeType: z.string().optional(),
  numSides: z.number().int().min(3).max(200).default(6),
  wobble: z.number().min(0).max(5).default(0.5),
  curviness: z.number().min(0).max(1).default(1),
  width: z.number().optional(),
  height: z.number().optional(),
  radiusFactor: z.number().min(0.001).max(5).default(0.4),
  radiusFactorX: z.number().min(0.001).max(5).optional(),
  radiusFactorY: z.number().min(0.001).max(5).optional(),
  noiseAmount: z.number().min(0).max(50).default(0.5),
  noiseSpeed: z.number().optional(),
  opacity: z.number().min(0).max(1).default(1),
  blendMode: z.string().default('source-over'),
  colors: z.array(z.string()).default([]),
  selectedColor: z.number().int().default(0),
  movementStyle: z.enum(['bounce', 'drift', 'still', 'orbit', 'spin']).default('bounce'),
  movementSpeed: z.number().min(0).max(10).default(1),
  movementAngle: z.number().default(45),
  scaleSpeed: z.number().min(0).max(1).default(0.05),
  scaleMin: z.number().min(0).max(5).default(0.2),
  scaleMax: z.number().min(0).max(10).default(1.5),
  spinAngle: z.number().default(0),
  variation: z.number().optional(),
  variationShape: z.number().optional(),
  variationAnim: z.number().optional(),
  variationColor: z.number().optional(),
  variationPosition: z.number().optional(),
  variationScale: z.number().optional(),
  seed: z.number().int().optional(),
  noiseSeed: z.number().int().optional(),
  useGlobalSeed: z.boolean().optional(),
  freq1: z.number().optional(),
  freq2: z.number().optional(),
  freq3: z.number().optional(),
  baseRadiusFactor: z.number().optional(),
  radiusBump: z.number().optional(),
  rotation: z.number().default(0),
  xOffset: z.number().min(-1).max(1).default(0),
  yOffset: z.number().min(-1).max(1).default(0),
  orbitCenterX: z.number().min(0).max(1).default(0.5),
  orbitCenterY: z.number().min(0).max(1).default(0.5),
  orbitAngle: z.number().default(0),
  orbitRadiusX: z.number().min(0).max(1).default(0.15),
  orbitRadiusY: z.number().min(0).max(1).default(0.15),
  nodes: z.array(z.object({ x: z.number(), y: z.number() })).nullable().optional(),
  syncNodesToNumSides: z.boolean().optional(),
  viewBoxMapped: z.boolean().optional(),
  imageBlur: z.number().min(0).max(100).default(0),
  imageBrightness: z.number().min(0).max(400).default(100),
  imageContrast: z.number().min(0).max(400).default(100),
  imageHue: z.number().min(0).max(360).default(0),
  imageSaturation: z.number().min(0).max(400).default(100),
  imageDistortion: z.number().min(0).max(200).default(0),
  position: positionSchema.default({ x: 0.5, y: 0.5, vx: 0, vy: 0, scale: 1, scaleDirection: 1 }),
  visible: z.boolean().default(true),
  vary: layerVariationSchema.optional(),
}).passthrough();
export type Layer = z.infer<typeof layerSchema>;

export const appStateSchema = z.object({
  isFrozen: z.boolean(),
  backgroundColor: z.string(),
  backgroundImage: z
    .object({
      src: z.string().nullable().optional(),
      opacity: z.number().min(0).max(1).default(1),
      fit: z.enum(['cover', 'contain', 'stretch']).default('cover'),
      enabled: z.boolean().default(false),
    })
    .optional(),
  globalBlendMode: z.string(),
  globalSeed: z.number().int(),
  globalSpeedMultiplier: z.number(),
  layers: z.array(layerSchema),
  selectedLayerIndex: z.number().int(),
  isOverlayVisible: z.boolean(),
  isNodeEditMode: z.boolean(),
  classicMode: z.boolean(),
  zIgnore: z.boolean(),
  randomizePalette: z.boolean(),
  randomizeNumColors: z.boolean(),
  colorFadeWhileFrozen: z.boolean(),
  syncLayerColorsToFirst: z.boolean(),
  parameterTargetMode: z.enum(['global', 'individual']),
  showLayerOutlines: z.boolean(),
  selectedLayerIds: z.array(z.string()).optional(),
  layerGroups: z
    .array(
      z.object({
        id: z.string(),
        name: z.string(),
        color: z.string().optional(),
        memberIds: z.array(z.string()),
      })
    )
    .optional(),
  editTarget: z
    .object({
      type: z.enum(['single', 'selection', 'group']),
      groupId: z.string().min(1).optional(),
      layerIds: z.array(z.string()).optional(),
    })
    .optional(),
  quickPreset: z.any().optional(),
  applyVariationInstantly: z.boolean().optional(),
  morphEnabled: z.boolean().optional(),
  morphRoute: z.array(z.number()).optional(),
  morphDurationPerLeg: z.number().optional(),
  morphEasing: z.string().optional(),
  morphLoopMode: z.string().optional(),
  morphMode: z.string().optional(),
}).passthrough();
export type AppState = z.infer<typeof appStateSchema>;

export const appSnapshotSchema = z.object({
  parameters: parameterArraySchema,
  appState: appStateSchema,
  midiMappings: z.record(z.string(), z.any()).optional(),
  exportMeta: z
    .object({
      version: z.string(),
      canvasWidth: z.number().optional(),
      canvasHeight: z.number().optional(),
      exportedAt: z.string().optional(),
    })
    .optional(),
  savedAt: z.string().optional(),
  version: z.string().optional(),
});
export type AppSnapshot = z.infer<typeof appSnapshotSchema>;
