export const PARAMETERS = [
  // Shape
  {
    id: 'numSides',
    label: 'Sides',
    type: 'slider',
    min: 3,
    max: 30,
    step: 1,
    defaultValue: 6,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'curviness',
    label: 'Curviness',
    type: 'slider',
    min: -10,
    max: 1,
    step: 0.01,
    defaultValue: -0.64,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'noiseAmount',
    label: 'Noise',
    type: 'slider',
    min: 0,
    max: 5,
    step: 0.01,
    defaultValue: 0.8,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },

  // Appearance
  {
    id: 'opacity',
    label: 'Opacity',
    type: 'slider',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 1.0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Appearance',
  },
  {
    id: 'blendMode',
    label: 'Blend Mode',
    type: 'dropdown',
    options: ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn', 'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity'],
    defaultValue: 'normal',
    isRandomizable: true,
    showInOverlay: true,
    group: 'Appearance',
  },

  // Transform
  {
    id: 'masterScale',
    label: 'Scale',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.01,
    defaultValue: 1,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Transform',
  },
  {
    id: 'shapeWidth',
    label: 'Width',
    type: 'slider',
    min: 0.1,
    max: 2,
    step: 0.01,
    defaultValue: 0.5,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Transform',
  },
  {
    id: 'shapeHeight',
    label: 'Height',
    type: 'slider',
    min: 0.1,
    max: 2,
    step: 0.01,
    defaultValue: 0.5,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Transform',
  },

  // Movement
  {
    id: 'movementStyle',
    label: 'Style',
    type: 'dropdown',
    options: ['bounce', 'drift'],
    defaultValue: 'bounce',
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'movementSpeed',
    label: 'Movement Speed',
    type: 'slider',
    min: 0,
    max: 0.02,
    step: 0.001,
    defaultValue: 0.001,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'movementAngle',
    label: 'Movement Angle',
    type: 'slider',
    min: 0,
    max: 360,
    step: 1,
    defaultValue: 45,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'scaleSpeed',
    label: 'Scale Speed',
    type: 'slider',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 0.05,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
];
