import { blendModes } from '../constants/blendModes';

export const PARAMETERS = [
  // Shape - matching old version exactly
  {
    id: 'numSides',
    label: 'Sides',
    type: 'slider',
    min: 3,
    max: 20,
    step: 1,
    defaultValue: 6,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'curviness',
    label: 'Curviness',
    type: 'slider',
    min: 0.0,
    max: 1.0,
    step: 0.05,
    defaultValue: 1.0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'wobble',
    label: 'Wobble',
    type: 'slider',
    min: 0.0,
    max: 1.0,
    step: 0.05,
    defaultValue: 0.5,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'noiseAmount',
    label: 'Noise',
    type: 'slider',
    min: 0,
    max: 8,
    step: 0.1,
    defaultValue: 0.5,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'radiusFactor',
    label: 'Size',
    type: 'slider',
    min: 0.01,
    max: 2.0,
    step: 0.01,
    defaultValue: 0.4,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'radiusFactorX',
    label: 'Size X',
    type: 'slider',
    min: 0.01,
    max: 2.0,
    step: 0.01,
    defaultValue: 0.4,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'radiusFactorY',
    label: 'Size Y',
    type: 'slider',
    min: 0.01,
    max: 2.0,
    step: 0.01,
    defaultValue: 0.4,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'xOffset',
    label: 'X Offset',
    type: 'slider',
    min: -0.5,
    max: 0.5,
    step: 0.001,
    defaultValue: 0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },
  {
    id: 'yOffset',
    label: 'Y Offset',
    type: 'slider',
    min: -0.5,
    max: 0.5,
    step: 0.001,
    defaultValue: 0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Shape',
  },

  // Layer Variation — split into three controls
  {
    id: 'variationPosition',
    label: 'Position Variation',
    type: 'slider',
    min: 0,
    max: 3,
    step: 0.1,
    defaultValue: 0.2,
    isRandomizable: true,
    showInOverlay: true,
    group: 'General',
  },
  {
    id: 'variationShape',
    label: 'Shape Variation',
    type: 'slider',
    min: 0,
    max: 3,
    step: 0.1,
    defaultValue: 0.2,
    isRandomizable: true,
    showInOverlay: true,
    group: 'General',
  },
  {
    id: 'variationAnim',
    label: 'Animation Variation',
    type: 'slider',
    min: 0,
    max: 3,
    step: 0.1,
    defaultValue: 0.2,
    isRandomizable: true,
    showInOverlay: true,
    group: 'General',
  },
  {
    id: 'variationColor',
    label: 'Colour Variation',
    type: 'slider',
    min: 0,
    max: 3,
    step: 0.1,
    defaultValue: 0.2,
    isRandomizable: true,
    showInOverlay: true,
    group: 'General',
  },
  {
    id: 'variationScale',
    label: 'Scale Variation',
    type: 'slider',
    min: -3,
    max: 3,
    step: 0.1,
    defaultValue: 0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'General',
  },

  // Appearance
  {
    id: 'opacity',
    label: 'Opacity',
    type: 'slider',
    min: 0,
    max: 1,
    step: 0.1,
    defaultValue: 0.8,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Appearance',
  },

  // Movement - keeping modern features
  {
    id: 'movementStyle',
    label: 'Movement Style',
    type: 'dropdown',
    options: ['bounce', 'drift', 'still', 'orbit', 'spin'],
    defaultValue: 'bounce',
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'movementSpeed',
    label: 'Movement Speed',
    type: 'slider',
    min: 0,
    max: 5,
    step: 0.01,
    defaultValue: 1,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'movementAngle',
    label: 'Movement Angle',
    type: 'slider',
    min: 0,
    max: 360,
    step: 1,
    defaultValue: 45,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'scaleSpeed',
    label: 'Z Scale Speed',
    type: 'slider',
    min: 0,
    max: 0.2,
    step: 0.001,
    defaultValue: 0.05,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'scaleMin',
    label: 'Z Scale Min',
    type: 'slider',
    min: 0.1,
    max: 2,
    step: 0.01,
    defaultValue: 0.2,
    isRandomizable: false,
    showInOverlay: true,
    group: 'Movement',
  },
  {
    id: 'scaleMax',
    label: 'Z Scale Max',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.01,
    defaultValue: 1.5,
    isRandomizable: false,
    showInOverlay: true,
    group: 'Movement',
  },

  // Advanced Shape Parameters (from old algorithm)
  {
    id: 'freq1',
    label: 'Frequency 1',
    type: 'slider',
    min: 0.5,
    max: 8,
    step: 0.1,
    defaultValue: 2,
    isRandomizable: true,
    showInOverlay: false,
    group: 'Advanced',
  },
  {
    id: 'freq2',
    label: 'Frequency 2',
    type: 'slider',
    min: 0.5,
    max: 8,
    step: 0.1,
    defaultValue: 3,
    isRandomizable: true,
    showInOverlay: false,
    group: 'Advanced',
  },
  {
    id: 'freq3',
    label: 'Frequency 3',
    type: 'slider',
    min: 0.5,
    max: 50,
    step: 0.5,
    defaultValue: 4,
    isRandomizable: true,
    showInOverlay: false,
    group: 'Advanced',
  },

  // Image Effects - keeping modern features
  {
    id: 'imageBlur',
    label: 'Blur',
    type: 'slider',
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Image Effects',
  },
  {
    id: 'imageBrightness',
    label: 'Brightness',
    type: 'slider',
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 100,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Image Effects',
  },
  {
    id: 'imageContrast',
    label: 'Contrast',
    type: 'slider',
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 100,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Image Effects',
  },
  {
    id: 'imageHue',
    label: 'Hue Shift',
    type: 'slider',
    min: 0,
    max: 360,
    step: 1,
    defaultValue: 0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Image Effects',
  },
  {
    id: 'imageSaturation',
    label: 'Saturation',
    type: 'slider',
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 100,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Image Effects',
  },
  {
    id: 'imageDistortion',
    label: 'Distortion',
    type: 'slider',
    min: 0,
    max: 50,
    step: 0.1,
    defaultValue: 0,
    isRandomizable: true,
    showInOverlay: true,
    group: 'Image Effects',
  },

  // Global controls (metadata only for Randomize All inclusion)
  // These provide isRandomizable flags for app-level controls toggled in App.jsx
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'global',
    isRandomizable: false,
    showInOverlay: false,
    group: 'Global',
  },
  {
    id: 'globalSpeedMultiplier',
    label: 'Global Speed',
    type: 'slider',
    min: 0,
    max: 5,
    step: 0.01,
    defaultValue: 1,
    isRandomizable: false,
    showInOverlay: false,
    group: 'Global',
  },
  {
    id: 'globalBlendMode',
    label: 'Global Blend Mode',
    type: 'dropdown',
    options: blendModes,
    defaultValue: 'source-over',
    isRandomizable: false,
    showInOverlay: false,
    group: 'Global',
  },
  {
    id: 'globalOpacity',
    label: 'Global Opacity',
    type: 'slider',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 1,
    isRandomizable: false,
    showInOverlay: false,
    group: 'Global',
  },
  {
    id: 'layersCount',
    label: 'Layers Count',
    type: 'slider',
    min: 1,
    max: 20,
    step: 1,
    defaultValue: 8,
    isRandomizable: false,
    showInOverlay: false,
    group: 'Global',
  },
];
